"""Add affected_sections to Holiday model

Revision ID: b4bf2fc0b1cc
Revises: dd897bd4524b
Create Date: 2025-06-28 16:20:19.998924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4bf2fc0b1cc'
down_revision = 'dd897bd4524b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holiday', schema=None) as batch_op:
        batch_op.add_column(sa.Column('affected_sections', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holiday', schema=None) as batch_op:
        batch_op.drop_column('affected_sections')

    # ### end Alembic commands ###
